{
  data: {
    books: [{
        bid: '1',
        sort: 'js',
        src: 'https://img1.doubanio.com/view/subject/l/public/s29478358.jpg',
        title: '深入理解ES6',
        author: '【美】Nicholas C. Zakas',
        pubtime: '2017-7-1',
        star: 5,
        readed: 2,
        summary: '高级程序设计的作者所写，很厚实，对ES6相关很多，各种知识点的细致讲解值得一看。',
      },
      {
        bid: '2',
        sort: 'js',
        src: 'https://img3.doubanio.com/view/subject/l/public/s28033372.jpg',
        title: '你不知道的JavaScript（上卷）',
        author: '[美] Kyle Simpson',
        pubtime: '2015-4',
        star: 5,
        readed: 2,
        summary: 'JavaScript语言有很多复杂的概念，但却用简单的方式体现出来。该系列前端必读',
      },
      {
        bid: '3',
        sort: 'js',
        src: 'https://img3.doubanio.com/view/subject/l/public/s28969600.jpg',
        title: '你不知道的JavaScript（中卷）',
        author: '[美] Kyle Simpson',
        pubtime: '2016-8',
        star: 5,
        readed: 2,
        summary: '深入理解语言内部的机制，全面介绍了JavaScript中常被人误解和忽视的重要知识点。本书是其中卷，主要介绍了类型、语法、异步和性能'
      },
      {
        bid: '4',
        sort: 'js',
        src: 'https://img1.doubanio.com/view/subject/l/public/s29656379.jpg',
        title: '你不知道的JavaScript（下卷）',
        star: 5,
        author: '[美] Kyle Simpson',
        pubtie: '2018-1-1',
        readed: 2,
        summary: 'JavaScript这门语言简单易用，很容易上手，但其语言机制复杂微妙，本书是其下卷，主要介绍了JavaScript入门知识和对ES6及未来发展趋势的展望。',
      },
      {
        bid: '5',
        sort: 'web',
        src: 'https://img3.doubanio.com/view/subject/l/public/s29728202.jpg',
        title: '现代前端技术解析',
        star: 5,
        author: '张成文',
        pubtime: '2017-4-1',
        readed: 2,
        summary: '这是一本以现代前端技术思想与理论为主要内容的书。《现代前端技术解析》在前端知识体系上做了很好的总结和梳理，涵盖了现代前端技术绝大部分的知识内容，起到一个启蒙作用'
      },
      {
        bid: '6',
        sort: 'web',
        src: 'https://img1.doubanio.com/view/subject/l/public/s29715097.jpg',
        title: '高效前端：Web高效编程与优化实践',
        readed: 2,
        author: '李银城',
        pubtime: '2018-3-15',
        star: 5,
        summary: '这不是一本单纯讲解前端编程技巧的书，而是一本注重思想提升和内功修炼的书。2018年强烈推荐',
      },
      {
        bid: '7',
        sort: 'js',
        src: 'https://img3.doubanio.com/view/subject/l/public/s29530690.jpg',
        title: 'ES6标准入门（第3版）',
        readed: 2,
        star: 5,
        author: '阮一峰',
        pubtime: '2017-9',
        summary: '本书根据ES2017标准，详尽介绍了所有新增的语法，对基本概念、设计目的和用法进行了清晰的讲解，给出了大量简单易懂的示例。',
      },
      {
        bid: '8',
        sort: 'js',
        src: 'https://img3.doubanio.com/view/subject/l/public/s28313380.jpg',
        title: 'JavaScript忍者秘籍',
        readed: 2,
        star: 5,
        author: 'John Resig / Bear Bibeault',
        pubtime: '2015-10',
        summary: '本书是jQuery库创始人编写的一本深入剖析JavaScript语言的书。本书共分四个部分，从准入训练、见习训练、忍者训练和火影训练四个层次讲述了逐步成为JavaScript高手的全过程。',
      },
      {
        bid: '9',
        sort: 'js',
        src: 'https://img3.doubanio.com/view/subject/l/public/s29689025.jpg',
        title: 'JavaScript忍者秘籍（第2版）',
        readed: 2,
        star: 5,
        pubtime: '2018-3-8',
        author: 'John Resig / Bear Bibeault / Josip Maras',
        summary: '本书从JavaScript语言及最重要的特性谈起，由浅入深地探讨了函数、作用域、闭包、生成器函数、对象、数组、模块化、JavaScript与Web页面的交互以及事件等主题',
      },
      {
        bid: '10',
        sort: 'js',
        src: 'https://img3.doubanio.com/view/subject/l/public/s8958650.jpg',
        title: 'JavaScript高级程序设计（第3版）',
        readed: 2,
        author: '尼古拉斯·泽卡斯',
        pubtime: '2012-3-29',
        star: 5,
        summary: '权威、经典，不需要多说，每个前端必读圣经。'
      },
      {
        bid: '11',
        sort: 'js',
        src: 'https://img3.doubanio.com/view/subject/l/public/s8958854.jpg',
        title: 'JavaScript权威指南(第6版)',
        readed: 2,
        star: 4,
        pubtime: '2012-4-1',
        author: '[美]|David Flanagan',
        summary: '有时间还是读吧，大四时懵懵懂懂读完的，更多的作用是工具，随时翻阅，现在的话更推荐ES6标准',
      },

      {
        bid: '12',
        sort: 'js',
        src: 'https://img1.doubanio.com/view/subject/l/public/s29735438.jpg',
        title: 'JavaScript核心技术开发解密',
        author: '阳波',
        pubtime: '32',
        star: 4,
        readed: 0,
        summary: '《JavaScript核心技术开发解密》针对JavaScript 中的核心技术，结合前沿开发实践，对JavaScr...'
      },
      {
        bid: '13',
        sort: 'htmlcss',
        src: 'https://img1.doubanio.com/view/subject/l/public/s28659699.jpg',
        title: 'CSS揭秘',
        author: '[希]LeaVerou',
        pubtime: '2016-4',
        star: 5,
        readed: 2,
        summary: '本书是一本注重实践的教程，作者为我们揭示了 47 个鲜为人知的 CSS 技巧，主要内容包括背景与边框、形状、 视觉...'
      },
      {
        bid: '14',
        sort: 'htmlcss',
        src: 'https://img3.doubanio.com/view/subject/l/public/s29554922.jpg',
        title: '指尖上行',
        author: '腾讯互动娱乐TGideas',
        pubtime: '60',
        star: 5,
        readed: 2,
        summary: '一本讲解前端移动端开发的书，很多细节和实例很友好，全彩质量也很高推荐一看'
      }, {
        bid: '15',
        sort: 'htmlcss',
        src: 'https://img3.doubanio.com/view/subject/l/public/s29345036.jpg',
        title: '前端体验设计',
        author: '[英]AndyClarke',
        pubtime: 'fined',
        star: 5,
        readed: 2,
        summary: '本书是Web设计畅销书《超越CSS》作者的最新力作，结合当前移动互联网下硬件的变化，以一个资深Web设计开发者的视...'
      },
      {
        bid: '16',
        sort: 'htmlcss',
        src: 'https://img1.doubanio.com/view/subject/l/public/s29137878.jpg',
        title: 'HTML5基础知识、核心技术与前沿案例',
        author: '刘欢',
        pubtime: '2016-10-1',
        star: 5,
        readed: 2,
        summary: '《HTML5基础知识、核心技术与前沿案例 》是一本引导初、中级学习者深入了解并有效掌握HTML5核心技巧的技术实战...'
      },
      {
        bid: '17',
        sort: 'htmlcss',
        src: 'https://img1.doubanio.com/view/subject/l/public/s29651678.jpg',
        title: 'CSS世界',
        author: '张鑫旭',
        pubtime: '2017-12',
        star: 5,
        readed: 2,
        summary: '本书从前端开发人员的需求出发，以“流”为线索，从结构、内容到美化装饰等方面，全面且深入地讲解前端开发人员必须了解和...'
      },
      {
        bid: '18',
        sort: 'js',
        src: 'https://img1.doubanio.com/view/subject/l/public/s29028887.jpg',
        title: '精通JavaScript（第2版）',
        author: '[美]JohnResig/[美]JohnPaxton/[美]RussFerguson',
        pubtime: '2016-9',
        star: 5,
        readed: 2,
        summary: '2006年，本书第1版问世，立刻脱颖而出，成为广大Web程序员心目中的经典，是提升JavaScript编程技能的必...'
      },
      {
        bid: '19',
        sort: 'js',
        src: 'https://img1.doubanio.com/view/subject/l/public/s29507769.jpg',
        title: 'JavaScript编程精粹',
        author: 'VedAntani',
        pubtime: '2017-8',
        star: 5,
        readed: 2,
        summary: '本书详细介绍讲述了JavaScript的基础知识以及一些系现代语言工具和库，例如jQuery、Underscore...'
      },
      {
        bid: '20',
        sort: 'js',
        src: 'https://img3.doubanio.com/view/subject/l/public/s29588992.jpg',
        title: 'JavaScript学习指南 第3版',
        author: '[美]EthanBrown布朗',
        pubtime: '2017-7',
        star: 5,
        readed: 2,
        summary: 'JavaScript是目前Web开发领域非常流行的一种编程语言，得到众多IT从业人员和编程爱好者的关注。本书分为2...'
      },
      {
        bid: '21',
        sort: 'js',
        src: 'https://img3.doubanio.com/view/subject/l/public/s29532960.jpg',
        title: '学习JavaScript数据结构与算法（第2版）',
        author: 'LoianeGroner',
        pubtime: '2017-9',
        star: 5,
        readed: 2,
        summary: '本书首先介绍了JavaScript 语言的基础知识以及ES6 和ES7 中引入的新功能，接下来讨论了数组、栈、队列...'
      },
      {
        bid: '22',
        sort: 'htmlcss',
        src: 'https://img3.doubanio.com/view/subject/l/public/s29295711.jpg',
        title: '响应式Web设计',
        author: '本·弗莱恩(BenFrain)',
        pubtime: '2017-2-1',
        star: 5,
        readed: 2,
        summary: '本书将当前Web 设计中热门的响应式设计技术与HTML5 和CSS3 结合起来，为读者全面深入地讲解了针对各种屏幕...'
      },
      {
        bid: '23',
        sort: 'js',
        src: 'https://img3.doubanio.com/view/subject/l/public/s28283431.jpg',
        title: '高性能JavaScript',
        author: '[美]尼古拉斯·泽卡斯',
        pubtime: '2015-8-1',
        star: 5,
        readed: 2,
        summary: '如果你使用 JavaScript 构建交互丰富的 Web 应用，那么 JavaScript 代码可能是造成你的We...'
      },
      {
        bid: '24',
        sort: 'web',
        src: 'https://img3.doubanio.com/view/subject/l/public/s29425641.jpg',
        title: '前端架构设计',
        author: '[美]MicahGodbolt',
        pubtime: '2017-4',
        star: 5,
        readed: 2,
        summary: '本书展示了一名成熟的前端架构师对前端开发全面而深刻的理解。作者结合自己在Red Hat公司的项目实战经历，探讨了前...'
      },
      {
        bid: '25',
        sort: 'js',
        src: 'https://img3.doubanio.com/view/subject/l/public/s27993864.jpg',
        title: 'JavaScript语言精粹',
        author: 'DouglasCrockford',
        pubtime: '2012-9-1',
        star: 5,
        readed: 2,
        summary: 'JavaScript 曾是“世界上最被误解的语言”，因为它担负太多的特性，包括糟糕的交互和失败的设计，但随着Aja...'
      },
      {
        bid: '26',
        sort: 'js',
        src: 'https://img3.doubanio.com/view/subject/l/public/s27984590.jpg',
        title: 'JavaScript面向对象编程指南（第2版）',
        author: '[加拿大]StoyanStefanov斯托扬',
        pubtime: '2014-12',
        star: 5,
        readed: 2,
        summary: '1.本书是唯一一本介绍JavaScript面向对象编程的图书。2.本书作者是知名的Web开发人员和作者。受到国内众...'
      },
      {
        bid: '27',
        sort: 'js',
        src: 'https://img3.doubanio.com/view/subject/l/public/s28065006.jpg',
        title: 'JavaScript设计模式与开发实践',
        author: '曾探',
        pubtime: '2015-5',
        star: 5,
        readed: 2,
        summary: '本书在尊重《设计模式》原意的同时，针对JavaScript语言特性全面介绍了更适合JavaScript程序员的了1...'
      },
      {
        bid: '28',
        sort: 'js',
        src: 'https://img3.doubanio.com/view/subject/l/public/s29114904.jpg',
        title: '实战 ES2015',
        author: '小问',
        pubtime: '2016-10-1',
        star: 4,
        readed: 2,
        summary: '在ES2015标准中的表现，以及利用ES2015中新特性在应用开发中的实践。以清晰的思路说明ES2015的详细特性...'
      },
      {
        bid: '29',
        sort: 'js',
        src: 'https://img3.doubanio.com/view/subject/l/public/s25808235.jpg',
        title: '编写可维护的JavaScript',
        author: '扎卡斯',
        pubtime: '2013-4',
        star: 4,
        readed: 2,
        summary: '《编写可维护的JavaScript》向开发人员阐述了如何在团队开发中编写具备高可维护性的JavaScript代码，...'
      },
      {
        bid: '30',
        sort: 'web',
        src: 'https://img3.doubanio.com/view/subject/l/public/s27283822.jpg',
        title: '图解HTTP',
        author: '[日]上野宣',
        pubtime: '2014-4-15',
        star: 5,
        readed: 2,
        summary: '本书对互联网基盘——HTTP协议进行了全面系统的介绍。作者由HTTP协议的发展历史娓娓道来，严谨细致地剖析了HTT...'
      },
      {
        bid: '31',
        sort: 'js',
        src: 'https://img3.doubanio.com/view/subject/l/public/s4677623.jpg',
        title: 'JavaScript DOM编程艺术 （第2版）',
        author: '[英]JeremyKeith/[加]JeffreySambells',
        pubtime: '2011-4',
        star: 4,
        readed: 2,
        summary: 'JavaScript是Web开发中最重要的一门语言，它强大而优美。无论是桌面开发，还是移动应用。JavaScrip...'
      },
      {
        bid: '32',
        sort: 'web',
        src: 'https://img3.doubanio.com/view/subject/l/public/s29384953.jpg',
        title: '客户端存储技术',
        author: '[美]RaymondCamden',
        pubtime: '2017-3',
        star: 4,
        readed: 2,
        summary: '客户端数据存储赋予浏览器快速访问数据的能力，从而节省网络流量并减轻服务器的压力，同时使离线应用程序得以真正实现。本...'
      },
      {
        bid: '33',
        sort: 'lib',
        src: 'https://img1.doubanio.com/view/subject/l/public/s29640359.jpg',
        title: '深入浅出Webpack',
        author: '吴浩麟',
        pubtime: '2018-1',
        star: 4,
        readed: 2,
        summary: '随着Web开发技术的发展，Webpack凭借其便于使用和涵盖面广的优势，成为目前非常流行的前端构建工具，是每位前端...'
      },
      {
        bid: '34',
        sort: 'htmlcss',
        src: 'https://img3.doubanio.com/view/subject/l/public/s29459174.jpg',
        title: 'CSS核心技术详解',
        author: '肖志华',
        pubtime: '2017-6',
        star: 4,
        readed: 2,
        summary: '《CSS核心技术详解》共分13章，第1章主要解答CSS中常见的问题，以及常用的技巧。第2～6章讲解了CSS的核心技...'
      },
      {
        bid: '35',
        sort: 'web',
        src: 'https://img3.doubanio.com/view/subject/l/public/s28094013.jpg',
        title: '高性能网站建设指南（第二版）',
        author: 'SteveSouders',
        pubtime: '2015-5',
        star: 4,
        readed: 2,
        summary: '《高性能网站建设指南：前端工程师技能精髓》结合Web 2.0以来Web开发领域的最新形势和特点，介绍了网站性能问题...'
      },
      {
        bid: '36',
        sort: 'htmlcss',
        src: 'https://img3.doubanio.com/view/subject/l/public/s29588624.jpg',
        title: 'CSS重构：样式表性能调优',
        author: '[美]SteveLindstrom',
        pubtime: '2017-11',
        star: 4,
        readed: 2,
        summary: '本书作为CSS重构指南，不仅展示了如何编写结构合理的CSS，以构建响应式、易于使用的网站，还介绍了如何用重构方法创...'
      },
      {
        bid: '37',
        sort: 'web',
        src: 'https://img1.doubanio.com/view/subject/l/public/s27287707.jpg',
        title: 'web性能实践日志',
        author: '［加］StoyanStefanov',
        pubtime: '2014-5',
        star: 4,
        readed: 2,
        summary: '《Web性能实践日志》包含了众多领域专家的关于 Web 性能的文章。其中包括了许多性能相关的主题，如开源工具、缓存...'
      },
      {
        bid: '38',
        sort: 'htmlcss',
        src: 'https://img3.doubanio.com/view/subject/l/public/s28319866.jpg',
        title: 'HTML5与CSS3权威指南（上册） （第3版）',
        author: '陆凌牛',
        pubtime: '2015-9-1',
        star: 4,
        readed: 2,
        summary: '本书是HTML 5与CSS 3领域公认的标杆之作，被读者誉为“系统学习HTML 5与CSS 3的最佳著作”和“We...'
      },
      {
        bid: '39',
        sort: 'htmlcss',
        src: 'https://img3.doubanio.com/view/subject/l/public/s27319226.jpg',
        title: '图解CSS3',
        author: '廖伟华',
        pubtime: '2014-7-1',
        star: 4,
        readed: 2,
        summary: '本书是CSS3领域的标准性著作，由资深Web前端工程师根据CSS3的最新技术标准撰写。内容极为全面、丰富和翔实，由...'
      },
      {
        bid: '40',
        sort: 'htmlcss',
        src: 'https://img3.doubanio.com/view/subject/l/public/s27104165.jpg',
        title: 'Head First HTML与CSS（第2版）',
        author: 'ElisabethRobson/EricFreeman',
        pubtime: '2013-9',
        star: 4,
        readed: 2,
        summary: '是不是已经厌倦了那些深奥的HTML书？你可能在抱怨，只有成为专家之后才能读懂那些书。那么，找一本新修订的《Head...'
      },
      {
        bid: '41',
        sort: 'htmlcss',
        src: 'https://img3.doubanio.com/view/subject/l/public/s27269296.jpg',
        title: '深入浅出Node.js',
        author: '朴灵',
        pubtime: '2013-12-1',
        star: 5,
        readed: 2,
        summary: '本书从不同的视角介绍了 Node 内在的特点和结构。由首章Node 介绍为索引，涉及Node 的各个方面，主要内容...'
      },
      {
        bid: '42',
        sort: 'lib',
        src: 'https://img3.doubanio.com/view/subject/l/public/s29587545.jpg',
        title: 'Vue.js 实战',
        author: '梁灏',
        pubtime: '2017-10-1',
        star: 4,
        readed: 2,
        summary: '本书以Vue.js 2为基础，以项目实战的方式来引导读者渐进式学习Vue.js。本书分为基础篇、进阶篇和实战篇三部...'
      },
      {
        bid: '43',
        sort: 'lib',
        src: 'https://img3.doubanio.com/view/subject/l/public/s29196005.jpg',
        title: 'React与Redux开发实例精解',
        author: '刘一奇',
        pubtime: '2016-12',
        star: 4,
        readed: 2,
        summary: '《React与Redux开发实例精解》共分四部分，全面介绍如何使用React 与Redux 进行Web 开发。第一...'
      },
      {
        bid: '44',
        sort: 'lib',
        src: 'https://img3.doubanio.com/view/subject/l/public/s29756650.jpg',
        title: 'React 进阶之路',
        author: 'efined',
        pubtime: '2018-4',
        star: 4,
        readed: 0,
        summary: '《React进阶之路》详细介绍了React技术栈涉及的主要技术。本书分为基础篇、进阶篇和实战篇三部分。基础篇主要介...'
      },
      {
        bid: '45',
        sort: 'lib',
        src: 'https://img3.doubanio.com/view/subject/l/public/s29162154.jpg',
        title: '深入React技术栈',
        author: '陈屹',
        pubtime: '2016-11-1',
        star: 4,
        readed: 1,
        summary: '全面讲述React技术栈的第一本原创图书，pure render专栏主创倾力打造覆盖React、Flux、Redu...'
      },
      {
        bid: '46',
        sort: 'lib',
        src: 'https://img1.doubanio.com/view/subject/l/public/s29105337.jpg',
        title: 'React Native入门与实战',
        author: '王利华/魏晓军/冯诚祺',
        pubtime: '2016-1',
        star: 4,
        readed: 0,
        summary: '本书共4部分，首先简要介绍了React Native的开发基础知识，然后介绍了React Native的API、组...'
      },
      {
        bid: '47',
        sort: 'lib',
        src: 'https://img3.doubanio.com/view/subject/l/public/s29456776.jpg',
        title: '深入浅出React和Redux',
        author: '程墨',
        pubtime: '2017-4-28',
        star: 4,
        readed: 2,
        summary: '本书作者是资深开发人员，有过多年的开发经验，总结了自己使用React和Redux的实战经验，系统分析React和R...'
      },
      {
        bid: '48',
        sort: 'lib',
        src: 'https://img1.doubanio.com/view/subject/l/public/s28026858.jpg',
        title: '锋利的jQuery',
        author: '单东林/张晓菲/魏然',
        pubtime: '2012-7-1',
        star: 4,
        readed: 2,
        summary: '《锋利的jQuery(第2版)》循序渐进地对jQuery的各种函数和方法调用进行了介绍，读者可以系统地掌握jQue...'
      },
      {
        bid: '49',
        sort: 'lib',
        src: 'https://img3.doubanio.com/view/subject/l/public/s29120035.jpg',
        title: 'React全栈：Redux+Flux+webpack+Babel整合开发',
        author: '张轩/杨寒星',
        pubtime: '2016-10-1',
        star: 4,
        readed: 2,
        summary: '《React全栈：Redux+Flux+webpack+Babel整合开发》从现代前端开发的标准、趋势和常用工具入...'
      },
      {
        bid: '50',
        sort: 'web',
        src: 'https://img1.doubanio.com/view/subject/l/public/s29470828.jpg',
        title: 'Web安全开发指南',
        author: '[美]JohnPaulMueller',
        pubtime: '2017-6',
        star: 4,
        readed: 0,
        summary: '本书分为5大部分，共17章，详细介绍了Web安全开发的必备知识，旨在让前端开发人员、设计师、产品经理等前端开发相关...'
      },
      {
        bid: '51',
        sort: 'htmlcss',
        src: 'https://img1.doubanio.com/view/subject/l/public/s28493028.jpg',
        title: 'SVG精髓（第2版）',
        author: '[美]J.DavidEisenberg/[加]AmeliaBellamy-Royds',
        pubtime: '2015-9',
        star: 4,
        readed: 0,
        summary: '《SVG精髓（第2版）》通过实例透彻讲解了SVG（可缩放矢量图形）这种标记语言的规范及应用。作者从简单的SVG应用...'
      },
      {
        bid: '52',
        sort: 'htmlcss',
        src: 'https://img3.doubanio.com/view/subject/l/public/s28687530.jpg',
        title: 'HTML5与WebGL编程',
        author: '[美]TonyParisi',
        pubtime: '2016-5',
        star: 4,
        readed: 0,
        summary: '本书介绍如何使用HTML5相关技术，如CSS3和新兴的Web图形标准WebGL，来创建具有高性能、震撼视觉效果的3...'
      },
      {
        bid: '53',
        sort: 'js',
        src: 'https://img1.doubanio.com/view/subject/l/public/s29537338.jpg',
        title: 'JavaScript框架设计 第二版',
        author: '司徒正美',
        pubtime: '2017-8',
        star: 4,
        readed: 1,
        summary: '内 容 提 要 本书全面讲解了JavaScript框架设计及相关的知识，主要内容包括种子模块、语言模块、浏览器嗅探...'
      },
      {
        bid: '54',
        sort: 'web',
        src: 'https://img3.doubanio.com/view/subject/l/public/s29227321.jpg',
        title: 'Node.js硬实战：115个核心技巧',
        author: '【美】AlexR.Young/【美】MarcHarter',
        pubtime: '2017-1',
        star: 4,
        readed: 1,
        summary: '《Node.js 硬实战：115 个核心技巧》是一本面向实战的Node.js 开发进阶指南。作为资深专家，《Nod...'
      },
      {
        bid: '55',
        sort: 'web',
        src: 'https://img3.doubanio.com/view/subject/l/public/s29460040.jpg',
        title: 'Web API的设计与开发',
        author: '[日]水野贵明',
        pubtime: '2017-6',
        star: 4,
        readed: 1,
        summary: '本书结合丰富的实例，详细讲解了Web API的设计、开发与运维相关的知识。第1章介绍Web API的概要；第2章详...'
      },
      {
        bid: '56',
        sort: 'web',
        src: 'https://img3.doubanio.com/view/subject/l/public/s29163923.jpg',
        title: 'SPA设计与架构：理解单页面Web应用',
        author: '【美】EmmitA.Scott',
        pubtime: '2016-11',
        star: 4,
        readed: 0,
        summary: 'SPA 开发技术的运用是当今Web 开发领域的热门趋势，但真正全面掌握该技术的开发者并不多。本书详尽阐述单页面We...'
      },
      {
        bid: '57',
        sort: 'lib',
        src: 'https://img3.doubanio.com/view/subject/l/public/s28031805.jpg',
        title: 'Three.js开发指南',
        author: 'JosDirksen',
        pubtime: '2015-3',
        star: 4,
        readed: 0,
        summary: '首部全面讲解Three.js开发的实用指南，循序渐进讲解Three.js的各种功能，通过大量交互示例，深入探索使用...'
      },
      {
        bid: '58',
        sort: 'web',
        src: 'https://img1.doubanio.com/view/subject/l/public/s29345559.jpg',
        title: '大型JavaScript应用最佳实践指南',
        author: '【加】AdamBoduch',
        pubtime: '2017-2',
        star: 4,
        readed: 1,
        summary: '《大型JavaScript应用最佳实践指南》以介绍扩展JavaScript 的特殊性，及影响其可扩展性的因素作为开...'
      },
      {
        bid: '59',
        sort: 'web',
        src: 'https://img3.doubanio.com/view/subject/l/public/s29665581.jpg',
        title: 'HTTP/2基础教程',
        author: 'StephenLudin/JavierGarza',
        pubtime: '2018-1',
        star: 4,
        readed: 1,
        summary: '让网站和应用更快速、更简洁、更稳健，从而有效提升用户体验，这无疑是众多开发者梦寐以求的。然而互联网发展日新月异，H...'
      },
      {
        bid: '60',
        sort: 'other',
        src: 'https://img3.doubanio.com/view/subject/l/public/s29402674.jpg',
        title: '尽在双11：阿里巴巴技术演进与超越',
        author: '阿里巴巴集团双11技术团队',
        pubtime: '2017-4',
        star: 4,
        readed: 0,
        summary: '“双 11”，诞生于杭州，成长于阿里，风行于互联网，成就于新经济，贡献于全世界。从 2009 年淘宝商城起，双 1...'
      },
      {
        bid: '61',
        sort: 'other',
        src: 'https://img3.doubanio.com/view/subject/l/public/s28281864.jpg',
        title: 'Web全栈工程师的自我修养',
        author: '余果',
        pubtime: '2015-9-1',
        star: 4,
        readed: 0,
        summary: '全栈工程师正成为 IT 行业的新秀，论是上市互联网公司还是创业公司，都对全栈工程师青睐有加。本书作者是腾讯公司高级...'
      },
      {
        bid: '62',
        sort: 'other',
        src: 'https://img3.doubanio.com/view/subject/l/public/s29605012.jpg',
        title: '互联网产品经理实务全书',
        author: '林富荣',
        pubtime: '2017-9',
        star: 4,
        readed: 0,
        summary: '《互联网产品经理实务全书》以作者十多年产品经理工作实践为基础，通过系统的理论结合丰富的实例，全面地介绍了软件产品开...'
      },
      {
        bid: '63',
        sort: 'other',
        src: 'https://img3.doubanio.com/view/subject/l/public/s28990046.jpg',
        title: '人人都是设计师',
        author: '[美]RebeccaHagen/[美]KimGolombisky',
        pubtime: '2016-9',
        star: 4,
        readed: 0,
        summary: '本书是一本为没有艺术背景的普通人所写的平面设计指导书，作者通过图文并茂的典型案例讲解了设计的主要原则和规则，主要内...'
      },
      {
        bid: '64',
        sort: 'other',
        src: 'https://img3.doubanio.com/view/subject/l/public/s4031723.jpg',
        title: '摄影师的视界',
        author: '[英]迈克尔·弗里曼',
        pubtime: '2009-9',
        star: 4,
        readed: 2,
        summary: '《摄影师的视界:迈克尔·弗里曼摄影构图与设计》内容简介：设计是创作一张成功照片的最重要因素之一。看到一幅潜在的好画...'
      },
      {
        bid: '65',
        sort: 'other',
        src: 'https://img1.doubanio.com/view/subject/l/public/s28984259.jpg',
        title: '体验设计白书',
        author: '张玳',
        pubtime: '2016-8',
        star: 4,
        readed: 2,
        summary: '本书讲述体验设计理念。主要内容包括：体验的定义和设计原则，体验设计的流程及具体实例，体验设计过程中会用到的工具、遇...'
      },
      {
        bid: '66',
        sort: 'other',
        src: 'https://img3.doubanio.com/view/subject/l/public/s29105145.jpg',
        title: '刻意练习',
        author: '[美]安德斯·艾利克森（AndersEricsson）/罗伯特·普尔（RobertPool）',
        pubtime: '2016-11-6',
        star: 4,
        readed: 2,
        summary: '4岁就会弹奏小提琴，童年时代写出多部名曲，只用一根弦也能弹完一首曲子，瞬间记住几百个随机数字，开平方比计算器还快，...'
      },
      {
        bid: '67',
        sort: 'other',
        src: 'https://img3.doubanio.com/view/subject/l/public/s29142312.jpg',
        title: '练习的心态',
        author: '[美]托马斯M.斯特纳（ThomasM.Sterner）',
        pubtime: '2016-11-30',
        star: 4,
        readed: 2,
        summary: '走路、说话、系鞋带、骑自行车??从小到大，我们在不断试错、学习新事物、练习新技能的过程中成长起来。人生中值得去做的...'
      },
      {
        bid: '68',
        sort: 'other',
        src: 'https://img3.doubanio.com/view/subject/l/public/s4646956.jpg',
        title: '程序员修炼之道',
        author: 'AndrewHunt/DavidThomas',
        pubtime: '2011-1',
        star: 4,
        readed: 1,
        summary: '《程序员修炼之道:从小工到专家》内容简介：《程序员修炼之道》由一系列独立的部分组成，涵盖的主题从个人责任、职业发展...'
      },
      {
        bid: '69',
        sort: 'other',
        src: 'https://img1.doubanio.com/view/subject/l/public/s4241529.jpg',
        title: '人人都是产品经理',
        author: '苏杰',
        pubtime: '2010年4月',
        star: 4,
        readed: 0,
        summary: '这是写给“-1到3岁的产品经理”的书，适合刚入门的产品经理、产品规划师、需求分析师，以及对做产品感兴趣的学生，用户...'
      },
      {
        bid: '70',
        sort: 'other',
        src: 'https://img3.doubanio.com/view/subject/l/public/s23486434.jpg',
        title: '写给大家看的设计书（第3版）',
        author: '[美]RobinWilliams',
        pubtime: '2009-1',
        star: 4,
        readed: 0,
        summary: '这本书出自一位世界级设计师之手。复杂的设计原理在书中凝炼为亲密性、对齐、重复和对比4 个基本原则。作者以其简洁明快...'
      },
      {
        bid: '71',
        sort: 'other',
        src: 'https://img3.doubanio.com/view/subject/l/public/s29527741.jpg',
        title: '硅谷革命',
        author: 'AndyHertzfeld',
        pubtime: '2017-9-1',
        star: 4,
        readed: 0,
        summary: '...'
      },
      {
        bid: '72',
        sort: 'other',
        src: 'https://img3.doubanio.com/view/subject/l/public/s4157180.jpg',
        title: '重构',
        author: '[美]MartinFowler',
        pubtime: '2010',
        star: 4,
        readed: 0,
        summary: '重构，一言以蔽之，就是在不改变外部行为的前提下，有条不紊地改善代码。多年前，正是本书原版的出版，使重构终于从编程高...'
      },
      {
        bid: '73',
        sort: 'other',
        src: 'https://img3.doubanio.com/view/subject/l/public/s26251595.jpg',
        title: '设计师要懂心理学',
        author: '[美]SusanWeinschenk',
        pubtime: '2013-5-1',
        star: 4,
        readed: 2,
        summary: '《设计师要懂心理学》出自国际知名的设计心理学博士Susan M. Weinschenk之手，内容实用，示例清晰，以...'
      },
      {
        bid: '74',
        sort: 'other',
        src: 'https://img3.doubanio.com/view/subject/l/public/s29105126.jpg',
        title: '学习之道',
        author: '[美]芭芭拉·奥克利（BarbaraOakley）',
        pubtime: '2016-11',
        star: 4,
        readed: 2,
        summary: '读完一本书，却不记得讲什么？美剧看了一箩筐，英语还是没长进？公众号、指导书、牛人帖，一个都没落，却还是没有形成自己...'
      },
      {
        bid: '75',
        sort: 'web',
        src: 'https://img3.doubanio.com/view/subject/l/public/s29408695.jpg',
        title: 'JavaScript数据可视化编程',
        author: '[美]StephenA.Thomas原作名:DataVisualizationwithJavaScript',
        pubtime: '2017-6',
        star: 5,
        readed: 1,
        summary: '数据可视化是实现数据价值的重要工具。数据可视化可以将抽象的数字累积转变成为图形、表单等，让普通人可以快速理解数据所...'
      },
      {
        bid: '76',
        sort: 'node',
        src: 'https://img3.doubanio.com/view/subject/l/public/s28333933.jpg',
        title: '代码逆袭 超实用的Node.js代码段',
        author: '周敏编著',
        pubtime: '2017-4',
        star: 4,
        readed: 0,
        summary: '《超实用的Node.js代码段》精选300余段Node.js代码，涵盖了服务器端脚本开发中的绝大多数要点、技巧与方...'
      },
      {
        bid: '77',
        sort: 'node',
        src: 'https://img3.doubanio.com/view/subject/l/public/s29705411.jpg',
        title: 'node.js设计模式（第2版）',
        author: '【爱尔兰】MarioCasciaro（马里奥•卡西罗）/【意大利】LucianoMammino（卢西安诺•马米诺）',
        pubtime: '2018-2',
        star: 4,
        readed: 0,
        summary: '《node.js设计模式（第2版）》通过大量示例形象地阐述了 Node.js 的哲学思想和设计模式。内容主要由六部...'
      },
      {
        bid: '78',
        sort: 'node',
        src: 'https://img3.doubanio.com/view/subject/l/public/s27274701.jpg',
        title: 'Node.js开发实战详解',
        author: '黄丹华',
        pubtime: '2014-4-1',
        star: 4,
        readed: 0,
        summary: '书由浅入深，全面、系统地介绍了Node.js开发技术。书中提供了大量有针对性的实例，供读者实践学习，同时提供了大量...'
      },
      {
        bid: '79',
        sort: 'node',
        src: 'https://img1.doubanio.com/view/subject/l/public/s29227277.jpg',
        title: 'Node.js微服务',
        author: '【美】DavidGonzalez',
        pubtime: '2017-1',
        star: 4,
        readed: 0,
        summary: '《Node.js微服务》对如何采用Node.js 及其生态工具进行微服务开发的最佳实践做了全面的介绍，内容包括对微...'
      },
      {
        bid: '80',
        sort: 'web',
        src: 'https://img1.doubanio.com/view/subject/l/public/s29537097.jpg',
        title: 'Web开发权威指南',
        author: '[美]ChrisAquino,/[美]ToddGandee',
        pubtime: '2017-9',
        star: 4,
        readed: 0,
        summary: '本书在知名培训机构Big Nerd Ranch 培训教材的基础上编写而成，囊括了JavaScript、HTML5、...'
      },
      {
        bid: '81',
        sort: 'web',
        src: 'https://img3.doubanio.com/view/subject/l/public/s26544945.jpg',
        title: 'HTML5 Canvas核心技术',
        author: 'DavidGeary',
        pubtime: '2013-5',
        star: 4,
        readed: 0,
        summary: '海报：...'
      },
      {
        bid: '82',
        sort: 'other',
        src: 'https://img3.doubanio.com/view/subject/l/public/s28322244.jpg',
        title: '算法（第4版）',
        author: '塞奇威克(RobertSedgewick)/韦恩(KevinWayne)',
        pubtime: '2012-10-1',
        star: 4,
        readed: 0,
        summary: '本书全面讲述算法和数据结构的必备知识，具有以下几大特色。     算法领域的经典参考书Sedgewick畅销著作...'
      }
    ]
  }
}
